name: Build iOS

on:
  workflow_dispatch:
    inputs:
      lanis_ref:
        description: 'Branch/Tag/Commit von lanis'
        default: 'alles'
        required: false
      liblanis_ref:
        description: 'Branch/Tag/Commit von liblanis'
        default: 'main'
        required: false

jobs:
  build-ios:
    name: Flutter iOS Build
    runs-on: macos-latest

    defaults:
      run:
        working-directory: lanis

    steps:
      - name: Checkout lanis (fork)
        uses: actions/checkout@v6
        with:
          repository: 13732348243521734/lanis
          ref: ${{ github.event.inputs.lanis_ref }}
          path: lanis

      - name: Checkout liblanis (fork)
        uses: actions/checkout@v6
        with:
          repository: 13732348243521734/liblanis
          ref: ${{ github.event.inputs.liblanis_ref }}
          path: liblanis

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Show Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Generate l10n
        run: dart run intl_utils:generate

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Package unsigned IPA
        run: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r -9 lanis-unsigned.ipa Payload

      - name: Upload iOS IPA
        uses: actions/upload-artifact@v4
        with:
          name: lanis-unsigned-ipa
          path: lanis/lanis-unsigned.ipa
          if-no-files-found: error
